# Generated by Django 5.1.3 on 2024-11-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testimonials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='icon',
            new_name='img',
        ),
    ]
